### ISSUE TITLE
Makefile

### ISSUE THREAD

**Issue by miliausha** [Mizky555/minishell#6]
you should add dependencies from your *.h files to your Makefile. If I change something on this files Makefile do nothing and I need to use command "make re' again. 

manage exit errors for example 'exit hjkjhj'

check this case echo $"PATH"

Try ctrl-C after running a blocking command like cat without arguments or grep “something“. Check this case please

miniopal : cd 42
errorminiopal :
I think better to write something meaningfull instead of just 'error'. In this case you should write 'No such file or directory'. Think about user, who doesn't know what you mean. And all errors must be followed by new line.

miniopal : cat | cat | ls
Makefile cat.c includes lol.c minishell srcs
^C
miniopal :
miniopal : miniopal :

Funny bug

Try ctrl-C after running a blocking command like cat without arguments or grep “something“.
Try ctrl-\ after running a blocking command like cat without arguments or grep “something“.

Fix redirects, cat >> file doesn't work

**Comment by miliausha** [comment]
manage exit errors for example 'exit hjkjhj'

**Comment by miliausha** [comment]
Try ctrl-C after running a blocking command like cat without arguments or grep “something“. Check this case please

**Comment by miliausha** [comment]
miniopal : cd 42
errorminiopal :

I think better to write something meaningfull instead of just 'error'. In this case you should write 'No such file or directory'. Think about user, who doesn't know what you mean. And all errors must be followed by new line.

**Comment by miliausha** [comment]
miniopal : cat | cat | ls
Makefile        cat.c           includes        lol.c           minishell       srcs
^C
miniopal :
miniopal : miniopal :

Funny bug

**Comment by hazamashoken** [comment]
- [ ] you should add dependencies from your *.h files to your Makefile. If I change something on this files Makefile do nothing and I need to use command "make re' again.

- [ ] manage exit errors for example 'exit hjkjhj'

- [ ] check this case echo $"PATH"

- [ ] Try ctrl-C after running a blocking command like cat without arguments or grep “something“. Check this case please

- [ ] miniopal : cd 42
errorminiopal :
I think better to write something meaningfull instead of just 'error'. In this case you should write 'No such file or directory'. Think about user, who doesn't know what you mean. And all errors must be followed by new line.

- [ ] miniopal : cat | cat | ls
Makefile cat.c includes lol.c minishell srcs
^C
miniopal :
miniopal : miniopal :

Funny bug

- [ ] Try ctrl-C after running a blocking command like cat without arguments or grep “something“.
- [ ] Try ctrl-\ after running a blocking command like cat without arguments or grep “something“.

- [ ] Fix redirects, cat >> file doesn't work
